language: ruby
node_js:
  - "6"
before_install:
  - npm install
  - pip install --user pillow
install: gem install jekyll html-proofer
script: npm run travis
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

